export default {
  jobTypes: ['Full-time', 'Part-time', 'Contract'],
  userGreeting: 'Hello, Shriprada',
  headerLine: 'Find your perfect job',
  headerSearchPlaceholder: 'What are you looking for?',
  popularJobsQuery: 'React Developer in india',
  GET: 'GET',
  search: 'search',
  popularJobs: 'Popular jobs',
  showAll: 'Show all',
  error: 'Error',
  noJobsFound: 'No jobs found',
  nearbyJobsQuery: 'React Developer in bangalore',
  nearbyJobs: 'Nearby jobs',
  jobDetailsQuery: 'job-details',
  tabs: ['About', 'Qualifications', 'Responsibilites'],
  sampleQualificationsTab: 'Example Qualifications Tab',
  sampleResponsibilitiesTab: 'Example Responsibilities Tab',
  noData: 'No data found!',
  jobOppurtunity: 'Job Opportunities',
};
